spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: C##bhau
    password: orcl
    url: jdbc:oracle:thin:@localhost:1521:xe
    
  jpa:
    hibernate:
      ddl-auto: update
      
    show-sql: true  